# Generated by Django 5.2.8 on 2026-01-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openjobs_app', '0002_user_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='duration',
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
