# Generated by Django 5.2.8 on 2025-11-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openjobs_app', '0002_user_avatar_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'candidate'), ('employer', 'employer'), ('admin', 'admin')], max_length=20),
        ),
    ]
