# Generated by Django 5.2.8 on 2026-01-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openjobs_app', '0003_remove_job_duration_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(choices=[('1_month', '1 tháng'), ('3_months', '3 tháng'), ('6_months', '6 tháng'), ('1_year', '1 năm'), ('2_years', '2 năm')], default='3_months', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='employment',
            unique_together={('user', 'job')},
        ),
    ]
