# Generated by Django 5.2.8 on 2026-01-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openjobs_app', '0004_job_duration_alter_employment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.CharField(choices=[('1_month', '1 tháng'), ('3_months', '3 tháng'), ('6_months', '6 tháng'), ('1_year', '1 năm'), ('2_years', '2 năm')], default='3_months', max_length=30),
        ),
    ]
