# Generated by Django 5.2.8 on 2026-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openjobs_app', '0005_alter_job_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='shifts',
            field=models.ManyToManyField(related_name='shifts', to='openjobs_app.workingtime'),
        ),
        migrations.DeleteModel(
            name='JobWorkingTime',
        ),
    ]
