# Generated by Django 5.2.8 on 2026-01-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openjobs_app', '0006_job_shifts_delete_jobworkingtime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appreciation',
            unique_together={('user', 'job')},
        ),
    ]
