# Generated by Django 5.2.8 on 2025-12-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openjobs_app', '0006_rename_name_employer_company_name_remove_user_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='phone_number',
        ),
    ]
