# Generated by Django 5.2.8 on 2026-01-15 16:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openjobs_app', '0007_alter_appreciation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='license',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
