# Generated by Django 5.2.8 on 2025-12-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openjobs_app', '0008_remove_image_url_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
    ]
