"""
Django settings for openjobs project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vb^z+)m$k45w@w%np#^m=hj*b0708&4uj1e!-zceo(x*qyior6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'openjobs_app.apps.OpenjobsAppConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'oauth2_provider',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'openjobs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'openjobs.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'openjobsdb',
        'USER': 'root',
        'PASSWORD': 'admin123@',
        'HOST': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'oauth2_provider.backends.OAuth2Backend',
]


import cloudinary
import cloudinary.api
import cloudinary.uploader

# cloudinary.config(
#     cloud_name= "dnbno2tkc",
#     api_key="896257422881191",
#     api_secret="X6BnafHH4o_-bojDL2gPXzPHQDE"
# )

cloudinary.config(
    cloud_name= "dyupzyqwj",
    api_key="497522642724389",
    api_secret="1qiLwjHVPTBX9_BYZKsRB2FfWJA",
    secure=True,
)



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
            'rest_framework.permissions.IsAuthenticated',
    ),

}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import pymysql
pymysql.install_as_MySQLdb()

AUTH_USER_MODEL = 'openjobs_app.User'

CLIENT_ID = 'SmLtbIKQLZLiYOZgsOxd3RoMyjjeM1NJHPLkW529'
CLIENT_SECRET = 'HibpcvIy2N4Rie1sN4yEX9nHkFthCKTKa8T7PQ3UQi7fE734Xfxq7vElgsXo9naA35TRyr3vvrv9xy1QXzcXCjDEsSpozNScZ3CaUmfcKa47HsAYbYDJm2NThrQojcaM'

APP_CONFIG ={
    'EMPLOYER_MIN_IMAGES':3
}

OAUTH2_INFO={
    "client_id":"8hVoyGhFlgsvy5v0gdFtoVWZeq3qCvOOzyL61agc",
    "client_secret":"KdNcz0vpECAlmZdJlJ9aTre2lCcGHhYVv7Hr2dWyV3LARWbML7MytZtSLk0UYq3ftCHgTKYHaz9A5TBrZ5Xi8eaGsyKVDergCPpDuMGzpjJ23X4FXMYdj1YrxPWjFsYz"
}

